#!/usr/bin/env ruby

require 'pecan'
require 'optparse'

commandHelp = <<HELP
Commands:
   set-repository :     Sets repository to store configuration to
See 'pecan COMMAND -h' for more information on a specific command.
HELP

global = OptionParser.new do |opts|
  opts.banner = "Usage: pecan [command] [options]"

  opts.on("-v", "--version", "Shows version") do
    puts Pecan::VERSION
    exit
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end

  opts.separator ""
  opts.separator commandHelp
end

commandOptions = {
    'set-repository' => OptionParser.new do |opts|
      opts.banner = "Usage: pecan set-repository [options]"

      opts.on("-h", "--help", "Prints this help") do
        puts opts
        exit
      end
    end
}

global.order!
command = ARGV.shift
commandOptions[command].order!

case command
  when 'set-repository' then puts "Not implemented yet"
end


