#!/usr/bin/env ruby

require 'pecan'
require 'optparse'

global = OptionParser.new do |opts|
  opts.banner = "Usage: pecan [command] [options]"

  opts.on("-v", "--version", "Shows version") do
    puts Pecan::VERSION
    exit
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end

  opts.separator "
Commands:
   repo :     sets repository to store configuration to

See 'pecan COMMAND -h' for more information on a specific command.
"

end

commandOptions = {
    'repo' => OptionParser.new do |opts|
      opts.banner = "Usage: pecan set-repository [options]"

      opts.on("-s", "--set REPOSITORY", "Sets repository to store configuration to") do |repo|
        PecanController.repositorySet(repo)
        puts "Current repository: #{repo}"
        exit
      end

      opts.on("-h", "--help", "Prints this help") do
        puts opts
        exit
      end
    end
}

global.order!
command = ARGV.shift
commandOptions[command].order!
